# aerc.conf — overrides only; see aerc(1) for defaults

[general]
default-save-path=~/tmp/

[ui]
stylesets-dirs=${XDG_CONFIG_HOME:-~/.config}/aerc/
styleset-name=dracula

[viewer]
pager=bat -p
alternatives=text/plain,text/html

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html=pandoc -f html -t plain | colorize
text/*=bat -fP --file-name="$AERC_FILENAME"
application/x-sh=bat -fP -l sh
image/*=catimg -w $(tput cols) -
subject,~Git(hub|lab)=lolcat -f
